Array indexing and Slicing of vectors

In [3]:
import numpy as np

In [7]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
#indexing
arr[1]  #+ve

np.int64(12)

In [12]:
#slicing
arr[2:6]

array([13, 14, 15, 16])

In [13]:
arr[:6]

array([11, 12, 13, 14, 15, 16])

In [14]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [16]:
#gap
arr[3:9:2]

array([14, 16, 18])

In [20]:
#reverse
print(arr[::-1])

[20 19 18 17 16 15 14 13 12 11]


indexing and slicing of matrix


In [23]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
print(arr[1]) #particular row

[ 6  7  8  9 10]


In [ ]:
print(arr[0,4]) #paticular idx

5


In [30]:
#slicing
arr[0:2,1:3 ]

array([[2, 3],
       [7, 8]])

In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
#first two row
arr[0:2, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
#last two rows
arr[4:,:]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
#col
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [36]:
#first two col
arr[:, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [37]:
 #last two col
arr[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [38]:
#reverse the entrie matrix
print(arr[::-1, ::-1])

[[30 29 28 27 26]
 [25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [39]:
arr[0:2, 2:4]

array([[3, 4],
       [8, 9]])

In [40]:
arr[4:,3:]

array([[24, 25],
       [29, 30]])

Boolean indexing

In [42]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
bool_indx = arr %2 ==0
bool_indx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [44]:
arr = arr[bool_indx]
arr

array([12, 14, 16, 18, 20])