In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,6,7,8,9])

In [3]:
a1+ a2

array([ 7,  8, 10, 12, 14])

In [4]:
a1-a2

array([-5, -4, -4, -4, -4])

In [5]:
a1* a2

array([ 6, 12, 21, 32, 45])

In [ ]:
a1 /a2

array([0.16666667, 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [7]:
a1 //a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,      64,    2187,   65536, 1953125])

In [9]:
a1 % a2

array([1, 2, 3, 4, 5])

Broadcasting

In [11]:
arr = np.array([10,20,30,40,50])

In [12]:
print(arr +5)

[15 25 35 45 55]


In [16]:
arr= np.array([[10,20,30,40],[12,13,14,15]])

In [17]:
print(arr +5)

[[15 25 35 45]
 [17 18 19 20]]


In [18]:
A = np.array([
    [1,2],
    [3,4]
])

print(A * 2)

[[2 4]
 [6 8]]


In [19]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


Deep and Shallow copy