In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,6,7,8,9])

In [3]:
a1+ a2

array([ 7,  8, 10, 12, 14])

In [4]:
a1-a2

array([-5, -4, -4, -4, -4])

In [5]:
a1* a2

array([ 6, 12, 21, 32, 45])

In [ ]:
a1 /a2

array([0.16666667, 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [7]:
a1 //a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,      64,    2187,   65536, 1953125])

In [9]:
a1 % a2

array([1, 2, 3, 4, 5])

Broadcasting

In [11]:
arr = np.array([10,20,30,40,50])

In [12]:
print(arr +5)

[15 25 35 45 55]


In [16]:
arr= np.array([[10,20,30,40],[12,13,14,15]])

In [17]:
print(arr +5)

[[15 25 35 45]
 [17 18 19 20]]


In [18]:
A = np.array([
    [1,2],
    [3,4]
])

print(A * 2)

[[2 4]
 [6 8]]


In [19]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


Deep and Shallow copy

In [ ]:
#shallow copy
arr = np.array([10,20,30,40]) 

In [45]:
view = arr.view()
print(view)

[10 20 30 40]


In [46]:
view[0] = 100
print(view)
print(arr)

[100  20  30  40]
[100  20  30  40]


In [47]:
#deep copy
arr = np.array([10,20,30,40]) 

In [48]:
copy = arr.copy()
print(copy)

[10 20 30 40]


In [50]:
copy[0]= 100
print(copy)
print(arr)

[100  20  30  40]
[10 20 30 40]


Matrix operations

In [64]:
A = np.array([[1,2],[4,5]])
B = np.array([[1,9],[4,3]])

In [65]:
A


array([[1, 2],
       [4, 5]])

In [66]:
B

array([[1, 9],
       [4, 3]])

In [67]:
A +B

array([[ 2, 11],
       [ 8,  8]])

In [68]:
A*B

array([[ 1, 18],
       [16, 15]])

In [69]:
A @ B #actual multipilcation

array([[ 9, 15],
       [24, 51]])

In [ ]:
np.dot(A,B) #dot multipilication

array([[ 9, 15],
       [24, 51]])

In [ ]:
A.T  #traspose

array([[1, 4],
       [2, 5]])

Advance array manipulation

stacking array

In [72]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [73]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [77]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(arr, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [81]:
np.vsplit(arr, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [86]:
np.split(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]