In [3]:
import numpy as np

Basic Array creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a= [1,2,3,4, "karan"]
a

[1, 2, 3, 4, 'karan']

In [8]:
np.array(a)

array(['1', '2', '3', '4', 'karan'], dtype='<U21')

In [ ]:
#1D
vector = np.array([1,2,3,4,5])
print(vector)
print(vector.shape)   #no of el

[1 2 3 4 5]
(5,)


In [ ]:
#2D
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.shape) #no of rows and col

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


Array generation function

In [15]:
#arrange
arr = np.arange(1,11,)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#zeroes  1D
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
#zeroes 2D
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
#ones
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [20]:
#ones matrix
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#linspace
arr = np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

Random generation function

In [6]:
np.random.rand(5)


array([0.33361813, 0.73305687, 0.50640957, 0.47118046, 0.54716509])

In [9]:
np.random.randn(5)

array([-0.45575973,  0.2667763 ,  0.58852516, -0.30305004,  1.33265884])

In [11]:
np.random.randint(10,20,10)

array([18, 10, 17, 13, 11, 16, 18, 15, 16, 11], dtype=int32)

In [12]:
np.random.random((2,3))

array([[0.03568647, 0.6571446 , 0.90229569],
       [0.80062388, 0.14763033, 0.06255971]])

In [13]:
np.random.choice([10,20,30,40])

np.int64(10)

arrays attributes

In [24]:
arr = np.array([[1,2,3],[4,5,9],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 9],
       [6, 7, 8]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.ndim

2

In [25]:
arr.itemsize

8

In [26]:
arr.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 9, 8]])

In [28]:
len(arr)

3

Array Methods


In [29]:
arr

array([[1, 2, 3],
       [4, 5, 9],
       [6, 7, 8]])

In [30]:
arr.min(
    
)

np.int64(1)

In [31]:
arr.max()

np.int64(9)

In [32]:
arr.sum()

np.int64(45)

In [ ]:
#sum of col =0
np.sum(arr, axis=0)


array([11, 14, 20])

In [34]:
#sum of rows=1
np.sum(arr, axis=1)

array([ 6, 18, 21])

In [35]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.argmax() #max el ka idx

np.int64(5)

In [ ]:
arr.argmin() #min el ka idx

np.int64(0)

Reshaping and resizing


In [38]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# arr= arr.resize(6,5) chnages original array itself
