In [1]:
import numpy as np

In [103]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
#sudoku

In [19]:
#for rows
b =np.sum(s, axis=1)
for i in b:
    if i != 45:
        print("sudoko is not valid")
        break
else:
    print("sudoku is valid")

sudoku is valid


In [17]:
#for columns
col=np.sum(s, axis=0)
for i in col:
    if i != 45:
        print("sudoko is not valid")
        break
else:
    print("sudoku is valid")

sudoku is valid


In [21]:
s.sum()

np.int64(405)

In [27]:
s[0:3,0:3]


array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [39]:
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(s[i:i+3, j:j+3])
        n =  s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


general questions

In [100]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [42]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [48]:
#Find the average age of students.
data[:,0:1].mean()

np.float64(18.4)

In [54]:
#Extract Math marks of all students.
data[:, 1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [56]:
#Find the highest Science mark.
data[:,2:].max()

np.int64(95)

In [68]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]


array([[19, 92, 88]])

In [70]:
#Increase Math marks of all students by 5.
num =data[:,1]
print(num +5)

[90 97 81 70 95]


import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [82]:
#Find how many students are younger than 19.
len(data[data[:,0] <19])

3

In [86]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)


array([81.6, 83.2])

In [94]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [101]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] <=75]= 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])