In [1]:
import numpy as np


In [3]:
x = np.array([1,2,3])
y= np.array([2,4,5])

In [5]:
print(x+y)
print(x-y)


[3 6 8]
[-1 -2 -2]


In [6]:
#absolute value
a= np.array([-3,3,4,-5,-5,-1])
print(np.absolute(a))

[3 3 4 5 5 1]


In [8]:
#binary operator
a= np.array([1,2,3,4])
b= np.array([9,2,2,4])
res = np.add(a,b)
print(res)

[10  4  5  8]


In [3]:
#Create a NumPy array containing numbers from 1 to 20.
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
#Create a 4 × 4 matrix filled with zeros.
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#Create a 5 × 5 identity matrix.
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
#Generate numbers from 10 to 100 with a step of 10.
np.arange(10,101,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [18]:
#Create a random 3×4 matrix between 1 and 100.
arr =np.random.randint(1,101,(3,4))
arr

array([[84, 26,  3, 55],
       [66, 32, 43, 63],
       [77,  8,  1,  3]], dtype=int32)

In [23]:
#Print shape, size, ndim and dtype.
arr = np.arange(24).reshape(4,6)

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)


(4, 6)
24
2
int64
