In [1]:
import numpy as np


In [3]:
x = np.array([1,2,3])
y= np.array([2,4,5])

In [5]:
print(x+y)
print(x-y)


[3 6 8]
[-1 -2 -2]


In [6]:
#absolute value
a= np.array([-3,3,4,-5,-5,-1])
print(np.absolute(a))

[3 3 4 5 5 1]


In [8]:
#binary operator
a= np.array([1,2,3,4])
b= np.array([9,2,2,4])
res = np.add(a,b)
print(res)

[10  4  5  8]
